services:
  db:
    image: mysql:latest
    container_name: "MySQL"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: admin 
      MYSQL_PASSWORD: admin@changeme
      MYSQL_ROOT_PASSWORD: root@passwd@changeme

  phpmyadmin:
    image: phpmyadmin
    container_name: "phpmyadmin"
    restart: always
    ports:
      - 8080:80
